apiVersion: v1
kind: Service
metadata:
  name: frontend-user-service
spec:
  type: LoadBalancer
  selector:
    app: react-express-mysql-frontend 
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
