apiVersion: v1
kind: Service
metadata:
  name: backend-frontend-service
spec:
  type: ClusterIP
  selector:
    app: react-express-mysql-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
